// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2acizIEROLtGqUVTveJEA7T4PYNPl50U',
    appId: '1:872323382862:web:c146dcf12471e075bf8d1f',
    messagingSenderId: '872323382862',
    projectId: 'vibe-water-tracker-2025',
    authDomain: 'vibe-water-tracker-2025.firebaseapp.com',
    storageBucket: 'vibe-water-tracker-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8vbVER8yC9p8db7oELim0acr1-b3jP4',
    appId: '1:872323382862:android:590f020aed3800b4bf8d1f',
    messagingSenderId: '872323382862',
    projectId: 'vibe-water-tracker-2025',
    storageBucket: 'vibe-water-tracker-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVpcqOcEcOM8oK-A_pbCNb3Zjwje1B5Q',
    appId: '1:872323382862:ios:685f1c93f19ee6a8bf8d1f',
    messagingSenderId: '872323382862',
    projectId: 'vibe-water-tracker-2025',
    storageBucket: 'vibe-water-tracker-2025.firebasestorage.app',
    iosBundleId: 'com.example.vibeWaterTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVpcqOcEcOM8oK-A_pbCNb3Zjwje1B5Q',
    appId: '1:872323382862:ios:685f1c93f19ee6a8bf8d1f',
    messagingSenderId: '872323382862',
    projectId: 'vibe-water-tracker-2025',
    storageBucket: 'vibe-water-tracker-2025.firebasestorage.app',
    iosBundleId: 'com.example.vibeWaterTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2acizIEROLtGqUVTveJEA7T4PYNPl50U',
    appId: '1:872323382862:web:3a5923bf69efe8f1bf8d1f',
    messagingSenderId: '872323382862',
    projectId: 'vibe-water-tracker-2025',
    authDomain: 'vibe-water-tracker-2025.firebaseapp.com',
    storageBucket: 'vibe-water-tracker-2025.firebasestorage.app',
  );
}
